// <auto-generated />
namespace DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Batch_Model_New_Porperty_AddedLike_Organization_Course_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Batch_Model_New_Porperty_AddedLike_Organization_Course_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201809250804293_Batch_Model_New_Porperty_AddedLike_Organization_Course_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
