// <auto-generated />
namespace DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addisdeletedfieldinallfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addisdeletedfieldinallfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201809200415008_Add isdeleted field in all fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
