// <auto-generated />
namespace DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Batch_Exam_Participant_Trainer_ModelCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Batch_Exam_Participant_Trainer_ModelCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201809170754149_Batch_Exam_Participant_Trainer_ModelCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
